// frontend/src/app/components/track-stats/track-stats.component.ts
import {Component, OnInit, ViewChild} from "@angular/core"
import {PlayerService} from "../../services/player.service"

@Component({
	selector: "track-stats",
	templateUrl: "./track-stats.component.html",
	styleUrls: ["./track-stats.component.sass"],
})
export class TrackStatsComponent implements OnInit {
	@ViewChild("title_div") title_div: HTMLDivElement
	@ViewChild("artist_div") artist_div: HTMLDivElement
	title_slide: boolean = false
	title_anim_duration: string
	title_anim_width: string
	artist_slide: boolean = false
	artist_anim_duration: string
	artist_anim_width: string

	constructor(public player_service: PlayerService) {}

	ngOnInit(): void {}

	ngAfterViewInit(): void {
		this.check_slide()
	}

	ngOnChanges(): void {
		this.clear_slide()
	}

	check_slide = () => {
		if (this.is_overflowing(this.title_div)) {
			this.title_slide = true
			this.title_anim_duration = this.title_div.scrollWidth / 30 + "s"
			this.title_anim_width =
				this.title_div.scrollWidth - this.title_div.offsetWidth + "px"
		}
		if (this.is_overflowing(this.artist_div)) {
			this.artist_slide = true
			this.artist_anim_duration = this.artist_div.scrollWidth / 30 + "s"
			this.artist_anim_width =
				this.artist_div.scrollWidth - this.artist_div.offsetWidth + "px"
		}
	}

	clear_slide = () => {
		this.title_slide = false
		this.title_anim_width = ""
		this.artist_slide = false
		this.artist_anim_width = ""
	}

	done_animating = () => {
		this.clear_slide()
		this.check_slide()
	}

	is_overflowing = (element: HTMLDivElement): boolean => {
		if (element) {
			return element.offsetWidth < element.scrollWidth
		}
		return false
	}
}

<div
	[ngClass]="{track_wrapper: true, slide: title_slide}"
	[ngStyle]="{animationDuration: title_anim_duration, width: title_anim_width}"
	#title_div
>
	<div class="slider" (transitionend)="done_animating()">
		{{ player_service.current_track?.title }}
	</div>
</div>
<div
	[ngClass]="{track_wrapper: true, small: true, slide: title_slide}"
	[ngStyle]="{animationDuration: artist_anim_duration, width: artist_anim_width}"
	#artist_div
>
	<div class="slider" (transitionend)="done_animating()">
		{{ player_service.current_track?.artist }}
	</div>
</div>

// frontend/src/components/track-stats/track-stats.tsx
import {Component, Host, h, Listen} from "@stencil/core"
import store from "../../global/store"

@Component({
	tag: "track-stats",
	styleUrl: "track-stats.css",
})
export class TrackStats {
	title_div: HTMLDivElement
	artist_div: HTMLDivElement

	async componentDidRender() {
		await this.check_slide()
	}

	async componentWillUpdate() {
		await this.clear_slide()
	}

	check_slide = async () => {
		if (this.is_overflowing(this.title_div)) {
			this.scroll_info(this.title_div)
		}
		if (this.is_overflowing(this.artist_div)) {
			this.scroll_info(this.artist_div)
		}
	}

	clear_slide = async () => {
		try {
			this.title_div.classList.remove("slide")
			this.title_div.style.width = ""
			this.artist_div.classList.remove("slide")
			this.artist_div.style.width = ""
		} catch {
			// Ignore
		}
	}

	@Listen("transitionend", {target: "body"})
	async done_animating() {
		await this.clear_slide()
		await this.check_slide()
	}

	scroll_info = (element: HTMLDivElement) => {
		element.classList.add("slide")
		element.style.animationDuration = element.scrollWidth / 30 + "s"
		element.style.width = element.scrollWidth - element.offsetWidth + "px"
	}

	is_overflowing = (element: HTMLDivElement) => {
		if (element) {
			return element.offsetWidth < element.scrollWidth
		}
	}

	render() {
		if (store.current_track.track_id) {
			return (
				<Host class="track_stats_host">
					<div class="track_wrapper">
						<div
							class="slider"
							ref={el => (this.title_div = el as HTMLDivElement)}
						>
							{store.current_track.title}
						</div>
					</div>
					<div class="track_wrapper small">
						<div
							class="slider"
							ref={el => (this.artist_div = el as HTMLDivElement)}
						>
							{store.current_track.artist}
						</div>
					</div>
				</Host>
			)
		}
	}
}
