// frontend/src/components/menu-toggle/menu-toggle.tsx
import {Component, h, Listen, Prop} from "@stencil/core"

@Component({
	tag: "menu-toggle",
	styleUrl: "menu-toggle.css",
	shadow: true,
})
export class MenuToggle {
	@Prop() showing: boolean = true
	@Prop() toggle: () => void
	@Prop() toggling: () => void

	@Listen("click")
	async toggle_menu() {
		this.toggling()
	}

	render() {
		let classes = "hamburger--arrowalt"
		if (this.showing) {
			classes += " is-active"
		}
		return (
			<button class={classes} type="button">
				<span class="hamburger-box">
					<span class="hamburger-inner" />
				</span>
			</button>
		)
	}
}

// frontend/src/app/components/menu-toggle/menu-toggle.component.ts
import {Component, HostListener, Input, OnInit} from "@angular/core"
import {MenuToggleService} from "../../services/menu-toggle.service"

@Component({
	selector: "menu-toggle",
	templateUrl: "./menu-toggle.component.html",
	styleUrls: ["./menu-toggle.component.sass"],
})
export class MenuToggleComponent implements OnInit {
	@Input() showing: boolean = true

	constructor(public menu_toggle_service: MenuToggleService) {}

	ngOnInit(): void {}

	@HostListener("click")
	async toggle_menu() {
		this.menu_toggle_service.toggle_nav()
	}
}

<button
	class="hamburger hamburger--arrowalt"
	[ngClass]="{'is-active': menu_toggle_service.nav_showing}"
	type="button"
>
	<span class="hamburger-box">
		<span class="hamburger-inner"></span>
	</span>
</button>
