// frontend/src/app/components/volume-dot/volume-dot.component.ts
import {Component, HostListener, Input, OnInit} from "@angular/core"
import {PlayerService} from "../../services/player.service"
import {print} from "../../utils"

@Component({
	selector: "volume-dot",
	templateUrl: "./volume-dot.component.html",
	styleUrls: ["./volume-dot.component.sass"],
})
export class VolumeDotComponent implements OnInit {
	@Input() parent: HTMLDivElement
	volume: number = 0.6
	active = false

	constructor(private player_service: PlayerService) {}

	ngOnInit(): void {
		this.volume = this.player_service.volume
	}

	@HostListener("touchstart")
	@HostListener("mousedown")
	async drag_start() {
		document.querySelector("body")!.classList.add("noselect")
		document.documentElement.style.overflow = "hidden"
		this.active = true
	}

	@HostListener("document:touchend")
	@HostListener("document:mouseup")
	async drag_end() {
		document.querySelector("body")!.classList.remove("noselect")
		document.documentElement.style.overflow = "auto"
		this.active = false
	}

	@HostListener("document:touchmove", ["$event"])
	@HostListener("document:mousemove", ["$event"])
	async drag(event: MouseEvent | TouchEvent) {
		if (this.active) {
			event.preventDefault()
			let parent_bounds = this.parent.getBoundingClientRect()
			let new_volume, client_y
			switch (event.type) {
				case "touchmove":
					client_y = (event as TouchEvent).touches[0].clientY
					break
				case "mousemove":
					client_y = (event as MouseEvent).clientY
					break
				default:
					return
			}
			new_volume =
				(parent_bounds.height - (client_y - parent_bounds.top)) /
				parent_bounds.height
			if (new_volume >= 0 && new_volume <= 1) {
				this.player_service.volume = new_volume
				this.volume = new_volume
			}
		}
	}
}

<div class="volume_dot" [ngStyle]="{bottom: (volume * 100).toFixed(0) + '%'}"></div>

// frontend/src/components/volume-dot/volume-dot.tsx
import {Component, Host, h, Element, Prop, Listen} from "@stencil/core"

@Component({
	tag: "volume-dot",
	styleUrl: "volume-dot.css",
})
export class VolumeDot {
	@Element() el: HTMLVolumeDotElement
	@Prop() volume: number
	@Prop() parent: HTMLDivElement
	@Prop() volume_handler: (volume: number) => void
	active = false
	vol_dot: HTMLDivElement

	constructor() {
		this.el.style.bottom = (this.volume * 100).toFixed(0) + "%"
	}

	@Listen("touchstart")
	@Listen("mousedown")
	async drag_start(event) {
		document.querySelector("body").classList.add("noselect")
		document.documentElement.style.overflow = "hidden"

		if (event.target === this.el || event.target === this.vol_dot) {
			this.active = true
		}
	}

	@Listen("touchend", {target: "body"})
	@Listen("mouseup", {target: "body"})
	async drag_end() {
		document.querySelector("body").classList.remove("noselect")
		document.documentElement.style.overflow = "auto"
		this.active = false
	}

	@Listen("touchmove", {target: "body"})
	@Listen("mousemove", {target: "body"})
	async drag(event) {
		if (this.active) {
			event.preventDefault()
			let parent_bounds = this.parent.getBoundingClientRect()
			let new_volume, client_y
			if (event.type === "touchmove") {
				client_y = event.touches[0].clientY
			} else {
				client_y = event.clientY
			}
			new_volume =
				(parent_bounds.height - (client_y - parent_bounds.top)) /
				parent_bounds.height
			if (new_volume >= 0 && new_volume <= 1) {
				this.volume_handler(new_volume)
				this.el.style.bottom = (new_volume * 100).toFixed(0) + "%"
			}
		}
	}

	render() {
		return (
			<Host class="volume_dot_host">
				<div
					class="volume_dot"
					ref={el => (this.vol_dot = el as HTMLDivElement)}
				/>
			</Host>
		)
	}
}
