// frontend/src/components/progress-dot/progress-dot.tsx
import {Component, Element, h, Host, Listen, Prop, Watch} from "@stencil/core"

@Component({
	tag: "progress-dot",
	styleUrl: "progress-dot.css",
	// shadow: true,
})
export class ProgressDot {
	@Element() el: HTMLProgressDotElement
	@Prop({mutable: true}) progress: number
	@Prop() parent: HTMLDivElement
	@Prop() seek_handler: (number) => void
	mew_position: number
	active = false
	progress_dot: HTMLDivElement

	@Listen("touchstart")
	@Listen("mousedown")
	async drag_start(event) {
		document.querySelector("body").classList.add("noselect")

		if (event.target === this.el || event.target === this.progress_dot) {
			this.active = true
		}
	}

	@Listen("touchend", {target: "body"})
	@Listen("mouseup", {target: "body"})
	async drag_end() {
		if (this.active) {
			document.querySelector("body").classList.remove("noselect")
			this.active = false
			this.seek_handler(this.mew_position)
		}
	}

	@Listen("touchmove", {target: "body"})
	@Listen("mousemove", {target: "body"})
	async drag(event) {
		if (this.active) {
			event.preventDefault()

			let parent_bounds = this.parent.getBoundingClientRect()
			let new_position, client_x
			if (event.type === "touchmove") {
				client_x = event.touches[0].clientX
			} else {
				client_x = event.clientX
			}
			new_position =
				(parent_bounds.width - (parent_bounds.right - client_x)) /
				parent_bounds.width
			if (new_position >= 0 && new_position <= 1) {
				this.mew_position = new_position * 100
				this.el.style.left = this.mew_position.toFixed(2) + "%"
			}
		}
	}

	@Watch("progress")
	async position_handler() {
		if (!this.active) {
			this.el.style.left = this.progress.toFixed(2) + "%"
		}
	}

	render() {
		return (
			<Host class="progress_dot_host">
				<div
					class="progress_dot"
					ref={el => (this.progress_dot = el as HTMLDivElement)}
				/>
			</Host>
		)
	}
}

// frontend/src/app/components/progress-dot/progress-dot.component.ts
import {Component, HostListener, Input, OnInit} from "@angular/core"
import {PlayerService} from "../../services/player.service"

@Component({
	selector: "progress-dot",
	templateUrl: "./progress-dot.component.html",
	styleUrls: ["./progress-dot.component.sass"],
})
export class ProgressDotComponent implements OnInit {
	@Input() parent: HTMLDivElement
	progress: number
	active = false

	constructor(private player_service: PlayerService) {}

	ngOnInit(): void {
		this.progress = this.player_service.seek
	}

	@HostListener("touchstart")
	@HostListener("mousedown")
	async drag_start() {
		document.querySelector("body")!.classList.add("noselect")

		this.active = true
	}

	@HostListener("touchend")
	@HostListener("mouseup")
	async drag_end() {
		if (this.active) {
			document.querySelector("body")!.classList.remove("noselect")
			this.active = false
			this.player_service.seek = this.progress
		}
	}

	@HostListener("touchmove", ["$event"])
	@HostListener("mousemove", ["$event"])
	async drag(event: MouseEvent | TouchEvent) {
		if (this.active) {
			event.preventDefault()

			let parent_bounds = this.parent.getBoundingClientRect()
			let new_position, client_x
			switch (event.type) {
				case "touchmove":
					client_x = (event as TouchEvent).touches[0].clientX
					break
				case "mousemove":
					client_x = (event as MouseEvent).clientX
					break
				default:
					return
			}
			new_position =
				(parent_bounds.width - (parent_bounds.right - client_x)) /
				parent_bounds.width
			if (new_position >= 0 && new_position <= 1) {
				this.progress = new_position * 100
			}
		}
	}
}

<div class="progress_dot" [ngStyle]="{left: progress.toFixed(2) + '%'}"></div>
